### ISSUE TITLE
cli tool and private registrations

### ISSUE THREAD

**Issue by msuhovec** [DataConservancy/dcs-packaging-tool#16]
Currently only publicly available registrations are available when used the cli tool to download packages (I guess this is expected behavior, as it is using the public API).

At some future point,  we would like to be able to download private registrations and projects, using the CurateND OSF login credentials.

I guess this is an enhancement request.

**Comment by emetsger** [comment]
Closed, see thread and resolution at https://github.com/DataConservancy/osf-packaging/issues/8
