### ISSUE TITLE
common api for registrations and projects

### ISSUE THREAD

**Issue by msuhovec** [DataConservancy/dcs-packaging-tool#17]
This is definitely in the "wish" category.

In our current CurateND use of the command line package download, the user provides the project or registration id , e.g. 7xtyz, and off we go. The problem we have is that we've no idea if the project identifier refers to a registration or an active project, and the two have different API endpoints- https://api.osf.io/v2/registrations vs https://api.osf.io/v2/nodes. Right now, we're only trying the registration route. We could try a head request on both before proceeding, but besides being a clunky solution, it probably won't work if we allow private registrations / projects.

If there were an easy way to distinguish between the two, or a common API endpoint, life would be grand.

**Comment by emetsger** [comment]
Closed, follow thread and resolution at https://github.com/DataConservancy/osf-packaging/issues/7.
