### ISSUE TITLE
cli tool: download in tmpdir vs /tmp

### ISSUE THREAD

**Issue by msuhovec** [DataConservancy/dcs-packaging-tool#18]
It appears that the current version of the cli package download downloads all of its files into /tmp
on the calling machine. For single-threaded exection, this is fine; however, for multithreaded execution, it is possible to overwrite  another session's download, or cause it to fail if downloads are run under different user ids. 

One possible solution to this is use a utility like Files.createTempDirectory, giving each session its own unique temp directory for downloads.

**Comment by emetsger** [comment]
Good call. We'll fix that!

**Comment by emetsger** [comment]
Closed, see thread and resolution at https://github.com/DataConservancy/osf-packaging/issues/6
