### ISSUE TITLE
Checksums do not match on Windows

### ISSUE THREAD

**Issue by Trumbore** [DataConservancy/dcs-packaging-tool#22]
Eight unit tests in dcs-packaging-tool-shared's util/ChecksumGeneratorVerifierTest (all the tests that do not have the word "Bad" in their name) fail due to checksum mismatch.  It is likely that the checksums are calculated differently on Windows than on Linux.

**Comment by birkland** [comment]
@Trumbore  It looks like these may be due to LF -> CRLF munging on Windows as well.  `.gitattributes` as mentioned in #23 will probably fix these too.

**Comment by emetsger** [comment]
@Trumbore when you are able, can you pull `master` and see if this is still an issue for you?

**Comment by Trumbore** [comment]
I got the latest code, but still saw the eight failures in this project.  I tested Aaron's suggestion by editing the line endings in the resource file.txt, and that indeed fixed the problem.  So, I think we should add a line to .gitattributes that handles Windows line endings for either all files *.txt or just this specific file.
