### ISSUE TITLE
Unit tests fail due to EOL differences on Windows

### ISSUE THREAD

**Issue by Trumbore** [DataConservancy/dcs-packaging-tool#23]
Five unit tests in dcs-packaging-tool-ser fail on Windows due to differing strings in a comparison.  The expected strings have "\r\n" for EOLs and the actual strings on Windows have "\n" for EOLs.

**Comment by birkland** [comment]
That should be fixable by adding a `.gitattributes` file to the root directory containing something like:

    *.sh text eol=lf
    *.cfg text eol=lf

That'll prevent it from going CRLF upon checkout

**Comment by emetsger** [comment]
@Trumbore is this an issue for you, or can this be closed?

**Comment by emetsger** [comment]
Fixed in a6315b42.
