### ISSUE TITLE
Unit tests fail on Windows due to uncaught exceptions

### ISSUE THREAD

**Issue by Trumbore** [DataConservancy/dcs-packaging-tool#24]
Four unit tests in dcs-packaging-tool-impl fail due to uncaught exceptions when creating a symbolic link.  The code catches UnsupportedOperationException, but on Windows the actual exception is FileSystemException, which is not handled.

**Comment by birkland** [comment]
@Trumbore  If I remember correctly, tests can pass if run as administrator (or if symlink privs are granted to the user), as symlinks are viewed as a security risk for some reason.  There's an `unprivileged` profile that simply skips those tests.

    mvn clean install -Punprivileged

**Comment by emetsger** [comment]
@Trumbore is this still an issue for you or can this be closed?

**Comment by Trumbore** [comment]
Yes, this problem still happens, but the fix is easy.  I am putting together a pull request that adds FileSystemException to the existing catch statements.
