### ISSUE TITLE
Invalid characters when attempting to bag

### ISSUE THREAD

**Issue by jschell42** [DataConservancy/dcs-packaging-tool#26]
We've been using the DCS packaging tool for a lot of Data Refuge work, but we run into problems when a dataset contains invalid characters. I have not been able to discern a pattern for what kind of sites or data uses these characters. I've been in contact with Hanh and have shared [5 datasets](https://drive.google.com/file/d/0B-IUBwgNFBwwemYtWVNRQ2Rwa3c/view?usp=sharing) that all threw up this error.

**Comment by htpvu** [comment]
@jschell42 Elliot started on this last week. We estimated that it'll take us until the end of this week for the update. I'll let you know if that changes.

**Comment by jschell42** [comment]
sounds good, thanks again for working on this!

\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

Justin Schell
Director, Shapiro Design Lab
University of Michigan Libraries
PhD, Comparative Studies in Discourse and Society
University of Minnesota
@612to651

**Comment by htpvu** [comment]
Hi Justin, 

We weren't able to finish off the update last Friday. Between interruption by other work and unexpected complexity in dealing with string manipulation, we're now planning to get this work done by the end of this iteration, which is April 12th. Please let me know if this delay would cause any trouble for you. 

thank you, 
-Hanh

**Comment by jschell42** [comment]
Nope, no trouble at all. Thanks for your continue work on this!

Justin

\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

Justin Schell
Director, Shapiro Design Lab
University of Michigan Libraries
PhD, Comparative Studies in Discourse and Society
University of Minnesota
@612to651

**Comment by emetsger** [comment]
Resolved in a01f055..54b08f (inclusive).  New release with this fix should be out in the next couple of days!

**Comment by jschell42** [comment]
Fantastic, thanks so much!
